### ISSUE TITLE
Can't run ares cli 

### ISSUE THREAD

**Issue by nickyzero** [webos-tools/cli#7]
When installing the CLI with npm, the following issue occurred and the `ares` command did not execute. It seems there is a problem with the npm path not being correctly set in the environment variables.

![20240625_111406](https://github.com/webos-tools/cli/assets/2037116/278750e8-9ed0-4c0e-89d9-6ee29acf9404)
![20240625_111201](https://github.com/webos-tools/cli/assets/2037116/a5e25780-7083-485e-b3b2-0eb5c868d4c4)

**Comment by YoungeunKim** [comment]
Please check the globally installed npm module path is in the environment variables by "echo $PATH".
You can use “npm config ls -l” command to check the path.

Thanks

**Comment by SeongCheolHeo** [comment]
In windows, please do below.
1. To get nodejs installation path, run below. 
C:\Users\admin\Downloads>npm config get prefix
C:\Program Files\nodejs

2. check your environment path whether it include above path("C:\Program Files\nodejs").
C:\Users\admin\Downloads>echo %PATH%
C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Users\admin\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Oracle\VirtualBox\;D:\Git\cmd;C:\Users\admin\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\admin\AppData\Local\Programs\Python\Python312\;C:\Users\admin\AppData\Local\Programs\Python\Launcher\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Users\admin\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\bin


![image](https://github.com/webos-tools/cli/assets/3174625/8acbd0cf-8cc7-482c-a567-7efd905d03dd)

Thanks

**Comment by nickyzero** [comment]
Thank you for your advice.
