### ISSUE TITLE
Typo in Code: Variable Name Correction

### ISSUE THREAD

**Issue by nickyzero** [webos-tools/cli#9]
https://github.com/webos-tools/cli/blob/17f173a6a6263ed4110ecdb636fd1f33bfadc293/files/templates/ose-sdk-templates/bootplate-web/index.html#L44C35-L44C46

Hello,

I have found a typo in the code while using the project. Below is the description of the typo and my suggested correction.

Problematic Code
```    
     *  If you change the name to helloParmas as you want, the contents will be reflected on the screen.
     */
    var helloApi = 'luna://com.domain.app.service/hello';
    var helloParams = '{"name":"webOS"}';
```

Problem Description
In the code above, the variable name `helloParmas` is misspelled in a comment line. The correct variable name should be `helloParams`.

Suggested Correction
```
     *  If you change the name to helloParams as you want, the contents will be reflected on the screen.
     */
    var helloApi = 'luna://com.domain.app.service/hello';
    var helloParams = '{"name":"webOS"}';
```

Please review and update the code accordingly.

Thank you.

**Comment by nhamkthd** [comment]
@nickyzero 
Thanks for your suggestion, we will update it in the next release.
